{ config, pkgs, modulesPath, lib, ... }:
# CLEANUP-02 note: pydantic-ai is NOT included in this agent flake because the
# teams-email-agent only runs teams_poll.py and email_m365.py (no AI summarization).
# The pydantic-ai version fix (0.x → 1.x) was applied to common-agent (which runs
# ai_summarize.py). If this agent ever needs AI capabilities, add the pydantic-ai
# 1.107.0 buildPythonPackage expression from common-agent/configuration.nix.

let
  py = pkgs.python3;

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  msgraph-sdk = py.pkgs.buildPythonPackage rec {
    pname = "msgraph_sdk";
    version = "1.58.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/m/msgraph_sdk/msgraph_sdk-1.58.0-py3-none-any.whl";
      hash = "sha256-n9qrWvIojWn78/74LCA9ORH2wxSurBXG0puxSusbtcg=";
    };
    propagatedBuildInputs = with py.pkgs; [
      httpx
      pydantic
    ];
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  azure-identity = py.pkgs.buildPythonPackage rec {
    pname = "azure_identity";
    version = "1.19.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/a/azure_identity/azure_identity-1.19.0-py3-none-any.whl";
      hash = "sha256-4/ZVjBgWktdQnwneEMylJ8fc5CZ3ZFT7l99RKkZSfoE=";
    };
    propagatedBuildInputs = with py.pkgs; [
      cryptography
      httpx
    ];
    doCheck = false;
  };

  pythonEnv = py.withPackages (ps: with ps; [
    pydantic
    httpx
    cryptography
    msgraph-sdk
    azure-identity
  ]);

in
{
  imports = [
    "${modulesPath}/virtualisation/proxmox-lxc.nix"
  ];

  # Proxmox LXC container settings
  # privileged=false: run as unprivileged container (security best practice)
  # manageNetwork=true: let NixOS manage networking (not Proxmox defaults)
  # manageHostName=true: NixOS controls hostname, not Proxmox injection
  proxmoxLXC = {
    privileged = false;
    manageNetwork = true;
    manageHostName = true;
  };

  # Disable DHCP — static IPv4 address is injected by Proxmox at container
  # creation time via `lxc-net` config (NOT hardcoded here per RESEARCH Anti-Patterns).
  # Setting networking.interfaces.eth0.ipv4.addresses here would conflict with
  # Proxmox's own IP injection and break container networking.
  networking.useDHCP = false;

  # Disable IPv6 — not used in the Suyam deployment environment
  networking.enableIPv6 = false;

  # Static network configuration via systemd-networkd
  # IP address is assigned by Proxmox at container creation — do NOT set
  # Address= here. Only DNS and gateway-level config is set statically.
  systemd.network.enable = true;
  systemd.network.networks."10-eth0" = {
    matchConfig.Name = "eth0";
    networkConfig = {
      DHCP = "no";
      IPv6AcceptRA = false;
      # DNS resolver: NOT set here — Proxmox injects DNS via lxc.net at
      # container-create time using the gateway from ProxmoxConfig.container_gateway.
      # Setting DNS here would bake the value into the rootfs tarball and silently
      # break container networking on deployments with a different gateway/resolver.
      #
      # If you need a build-time DNS default (e.g. for offline builds), set it via:
      #   networking.nameservers = [ "your.dns.ip" ];
      # and also run `nix flake update` to bust the flake.lock build cache before
      # rebuilding the template — the cache key is the flake.lock hash.
    };
  };

  # Prevent 90-second boot hang waiting for network to come online
  # (RESEARCH.md Pitfall 5 — wait-online stalls boot when IP is static/late)
  systemd.network.wait-online.enable = false;

  # Python runtime for workflow step execution — all packages baked into image
  environment.systemPackages = [ pythonEnv ];

  system.activationScripts.suyamScripts = ''
    mkdir -p /opt/suyam
    cp ${./scripts/teams_poll.py} /opt/suyam/teams_poll.py
    chmod +x /opt/suyam/teams_poll.py
    cp ${../common-agent/scripts/email_m365.py} /opt/suyam/email_m365.py
    chmod +x /opt/suyam/email_m365.py
  '';

  system.activationScripts.suyamSecrets = {
    text = ''
      if [ -d /run/secrets ]; then
        env_file=/etc/profile.d/suyam-secrets.sh
        echo "# Auto-generated by suyam activation -- do not edit" > "$env_file"
        for f in /run/secrets/SUYAM_CRED_*; do
          [ -f "$f" ] || continue
          varname=$(basename "$f")
          varval=$(cat "$f")
          # POSIX-safe quoting: single-quote wrap with embedded-single-quote escaping.
          escaped=$(printf '%s' "$varval" | sed "s/'/'\\\\'''/g")
          printf "export %s='%s'\n" "$varname" "$escaped" >> "$env_file"
        done
        chmod 600 "$env_file"
      fi
    '';
    deps = [];
  };

  # NixOS version — pin to 25.11 (stable channel used in this project)
  system.stateVersion = "25.11";
}
