{ config, pkgs, modulesPath, lib, ... }:

let
  py = pkgs.python3;

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  pydantic-graph = py.pkgs.buildPythonPackage rec {
    pname = "pydantic_graph";
    version = "0.0.36";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/p/pydantic_graph/pydantic_graph-0.0.36-py3-none-any.whl";
      hash = "sha256-/MLDkWjXlGb9vvb1TjwH8136pFXVgfsZDuzHf6ZbO5I=";
    };
    propagatedBuildInputs = with py.pkgs; [ pydantic ];
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  pydantic-ai-slim = py.pkgs.buildPythonPackage rec {
    pname = "pydantic_ai_slim";
    version = "0.0.36";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/p/pydantic_ai_slim/pydantic_ai_slim-0.0.36-py3-none-any.whl";
      hash = "sha256-8M/mXcR4j1iMImxp5WtkPxLfX5sKBrDV2eEw0eiI3Uk=";
    };
    propagatedBuildInputs = with py.pkgs; [
      pydantic
      httpx
      anyio
      typing-extensions
      pydantic-graph
    ];
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  groq-sdk = py.pkgs.buildPythonPackage rec {
    pname = "groq";
    version = "0.28.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/g/groq/groq-0.28.0-py3-none-any.whl";
      hash = "sha256-xvhmODccLLosozcjLnbI1BLnWWXtfjBY0wyapd/oQwM=";
    };
    propagatedBuildInputs = with py.pkgs; [
      httpx
      pydantic
      distro
      anyio
    ];
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  # jiter is a Rust extension wheel — use manylinux x86_64 cp312 build
  jiter = py.pkgs.buildPythonPackage rec {
    pname = "jiter";
    version = "0.9.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/cp312/j/jiter/jiter-0.9.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      hash = "sha256-/KGgKtYOwwuyMPZbwB9hHIYIsC0mn5mLwpzKhhmpGdw=";
    };
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  anthropic-sdk = py.pkgs.buildPythonPackage rec {
    pname = "anthropic";
    version = "0.105.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/a/anthropic/anthropic-0.105.0-py3-none-any.whl";
      hash = "sha256-BWWXXzeorHvc+XwgAqpbEzN2wVfZJlmXchx/Ex5pck0=";
    };
    propagatedBuildInputs = with py.pkgs; [
      httpx
      pydantic
      typing-extensions
      anyio
      jiter
    ];
    doCheck = false;
  };

  pythonEnv = py.withPackages (ps: with ps; [
    pydantic
    httpx
    anyio
    typing-extensions
    distro
    pydantic-graph
    pydantic-ai-slim
    groq-sdk
    jiter
    anthropic-sdk
  ]);

in
{
  imports = [
    "${modulesPath}/virtualisation/proxmox-lxc.nix"
  ];

  proxmoxLXC = {
    privileged = false;
    manageNetwork = true;
    manageHostName = true;
  };

  networking.hostName = "common-agent";
  networking.useDHCP = false;
  networking.enableIPv6 = false;

  # IP address, gateway, and DNS are injected by Proxmox at container creation time
  # via the net0=...,ip=<cidr>,gw=<gw> create parameter — do NOT hardcode here.
  # Hardcoding causes IP collisions for concurrent containers and breaks any deployment
  # not using the same subnet. See teams-email-agent/configuration.nix for the correct pattern.

  services.resolved.enable = false;
  systemd.network.wait-online.enable = false;

  environment.systemPackages = [ pythonEnv ];

  system.activationScripts.suyamScripts = ''
    mkdir -p /opt/suyam
    cp ${./scripts/ai_summarize.py} /opt/suyam/ai_summarize.py
    chmod +x /opt/suyam/ai_summarize.py
    cp ${./scripts/http_request.py} /opt/suyam/http_request.py
    chmod +x /opt/suyam/http_request.py
  '';

  system.activationScripts.suyamSecrets = {
    text = ''
      if [ -d /run/secrets ]; then
        env_file=/etc/profile.d/suyam-secrets.sh
        echo "# Auto-generated by suyam activation -- do not edit" > "$env_file"
        for f in /run/secrets/SUYAM_CRED_*; do
          [ -f "$f" ] || continue
          varname=$(basename "$f")
          varval=$(cat "$f")
          # POSIX-safe quoting: single-quote wrap with embedded-single-quote escaping.
          # printf '%q' is bash-only and silently degrades to literal '%q' in dash
          # (the POSIX sh on NixOS). This approach is safe for all POSIX shells.
          escaped=$(printf '%s' "$varval" | sed "s/'/'\\\\'''/g")
          printf "export %s='%s'\n" "$varname" "$escaped" >> "$env_file"
        done
        chmod 600 "$env_file"
      fi
    '';
    deps = [];
  };

  system.stateVersion = "25.11";
}
