{ config, pkgs, modulesPath, lib, ... }:

let
  py = pkgs.python3;

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  msgraph-sdk = py.pkgs.buildPythonPackage rec {
    pname = "msgraph_sdk";
    version = "1.58.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/m/msgraph_sdk/msgraph_sdk-1.58.0-py3-none-any.whl";
      hash = "sha256-n9qrWvIojWn78/74LCA9ORH2wxSurBXG0puxSusbtcg=";
    };
    propagatedBuildInputs = with py.pkgs; [
      httpx
      pydantic
    ];
    doCheck = false;
  };

  # nix-prefetch: run nix build once to get real hash, paste here, rebuild
  azure-identity = py.pkgs.buildPythonPackage rec {
    pname = "azure_identity";
    version = "1.19.0";
    format = "wheel";
    src = pkgs.fetchurl {
      url = "https://files.pythonhosted.org/packages/py3/a/azure_identity/azure_identity-1.19.0-py3-none-any.whl";
      hash = "sha256-4/ZVjBgWktdQnwneEMylJ8fc5CZ3ZFT7l99RKkZSfoE=";
    };
    propagatedBuildInputs = with py.pkgs; [
      cryptography
      httpx
    ];
    doCheck = false;
  };

  pythonEnv = py.withPackages (ps: with ps; [
    pydantic
    httpx
    cryptography
    msgraph-sdk
    azure-identity
  ]);

in
{
  imports = [
    "${modulesPath}/virtualisation/proxmox-lxc.nix"
  ];

  proxmoxLXC = {
    privileged = false;
    manageNetwork = true;
    manageHostName = true;
  };

  networking.hostName = "email-agent";
  networking.useDHCP = false;
  networking.enableIPv6 = false;

  networking.interfaces.eth0.ipv4.addresses = [{ address = "10.10.0.101"; prefixLength = 24; }];
  networking.defaultGateway = "10.10.0.1";
  networking.nameservers = [ "8.8.8.8" "1.1.1.1" ];

  services.resolved.enable = false;
  systemd.network.wait-online.enable = false;

  environment.systemPackages = [ pythonEnv ];

  system.activationScripts.suyamScripts = ''
    mkdir -p /opt/suyam
    cp ${./scripts/email_smtp.py} /opt/suyam/email_smtp.py
    chmod +x /opt/suyam/email_smtp.py
    cp ${../common-agent/scripts/email_m365.py} /opt/suyam/email_m365.py
    chmod +x /opt/suyam/email_m365.py
  '';

  system.activationScripts.suyamSecrets = {
    text = ''
      if [ -d /run/secrets ]; then
        env_file=/etc/profile.d/suyam-secrets.sh
        echo "# Auto-generated by suyam activation -- do not edit" > "$env_file"
        for f in /run/secrets/SUYAM_CRED_*; do
          [ -f "$f" ] || continue
          varname=$(basename "$f")
          varval=$(cat "$f")
          # POSIX-safe quoting: single-quote wrap with embedded-single-quote escaping.
          escaped=$(printf '%s' "$varval" | sed "s/'/'\\\\'''/g")
          printf "export %s='%s'\n" "$varname" "$escaped" >> "$env_file"
        done
        chmod 600 "$env_file"
      fi
    '';
    deps = [];
  };

  system.stateVersion = "25.11";
}
